server:
  port: 8090

# db layer
spring:
  datasource:
    url: jdbc:postgresql://food-tech.cfaqce9zt6sm.eu-central-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: burhanorkun
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        format_sql: true
  data:
    jpa:
      repositories:
        enabled: true

